#! /usr/bin/env python3

from os import makedirs, path, mkdir

class CreateApp:
    def __init__(self):
        self.project_name = input('\033[1;32;40mProject name: ')
        self.main_path = '{}'.format(self.project_name)
        self.app_path = '{}/app'.format(self.main_path)
        self.test_path = '{}/tests'.format(self.main_path)
        self.template_path = '{}/template'.format(self.app_path)
        self.static_path = '{}/static'.format(self.app_path)


    def create_main_dir(self):
        makedirs('{}/app/'.format(self.project_name))
        mkdir('{}/tests/'.format(self.project_name))
        return 'Project name: {} is create'.format(self.project_name)


    def file_creator(self):
        with open('{}/app.py'.format(self.project_name), 'x') as app,\
             open('{}/__init__.py'.format(self.project_name), 'x') as app,\
             open('{}/test.py'.format(self.test_path), 'x') as app,\
             open('{}/forms.py'.format(self.app_path), 'x') as app,\
             open('{}/models.py'.format(self.app_path), 'x') as app,\
             open('{}/index.html'.format(self.template_path), 'x') as app,\
             open('{}/css/style.css'.format(self.static_path), 'x') as app:
            app.close()
            

        return 'Main file is created'


    def app_dirs(self):
        mkdir(path.join(self.app_path, 'template'))
        mkdir(path.join(self.app_path, 'static'))
        mkdir(path.join(self.app_path, 'auth'))
        
        return 'directory is create'


    def static_dirs(self):
        mkdir(path.join(self.static_path, 'css'))
        mkdir(path.join(self.static_path, 'img'))
        mkdir(path.join(self.static_path, 'js'))


    def create(self):
        try:
            self.create_main_dir()
            self.app_dirs()
            self.static_dirs()
            self.file_creator()
            
            return '\033[1;32;40mThe project: {} was created successfully'.format(self.project_name)
        
        except Exception as e:
            return '\033[1;31;40m{}\nProject name is not valid or already exist'.format(e)



if __name__ == '__main__':
    app = CreateApp()
    print(app.create())
